;;; -*- Mode: LISP; Package: CHAOS; Base: 8 -*-
;;; *** THIS FILE WAS AUTOMATICALLY GENERATED BY A PROGRAM, DO NOT EDIT IT ***
;;; Host table made from SERVER: /users/greggilley/mit-cadr/branches/ggilley/lisp/chaos/hosts.text by ggilley at 12/08/12 14:26:18
(SI:DEFINE-HOST "SERVER" ':HOST-NAMES '("SERVER") ':SYSTEM-TYPE ':UNIX ':CHAOS '(404))
(SI:DEFINE-HOST "CADR" ':HOST-NAMES '("CADR") ':SYSTEM-TYPE ':LISPM ':CHAOS '(401))
